### ISSUE TITLE
program freezes sometimes when changing preset

### ISSUE THREAD

**Issue by roffe** [roffe/txlogger#13]
Program can randomly freeze when changing preset.

![image](https://github.com/roffe/txlogger/assets/5434736/a21aa863-7085-426c-87ad-29580b7c62e4)

**Comment by Schottis** [comment]
Yes. Happens for me too. Workaround was to change ECU then change preset, then change ECU back again.

**Comment by roffe** [comment]
Have not seen this in a while so closing
